# ~/.config/starship.toml

# Use custom format
format = """[$directory](regular green)[$git_branch$git_state$git_status](italic white)  """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false
